name: Sync to Azure DevOps

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Azure DevOps
        run: |
          git remote add azure https://anything:${{ secrets.AZURE_DUPE}}@dev.azure.com/growthwizard/wp-canvas/_git/wp-canvas
          git push azure --mirror
